/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as EbooksIndexRouteImport } from './routes/ebooks.index'
import { Route as EbooksIdRouteImport } from './routes/ebooks.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksIndexRoute = EbooksIndexRouteImport.update({
  id: '/ebooks/',
  path: '/ebooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksIdRoute = EbooksIdRouteImport.update({
  id: '/ebooks/$id',
  path: '/ebooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/ebooks/$id': typeof EbooksIdRoute
  '/ebooks/': typeof EbooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/ebooks/$id': typeof EbooksIdRoute
  '/ebooks': typeof EbooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/ebooks/$id': typeof EbooksIdRoute
  '/ebooks/': typeof EbooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/blogs' | '/ebooks/$id' | '/ebooks/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/blogs' | '/ebooks/$id' | '/ebooks'
  id: '__root__' | '/' | '/about' | '/blogs' | '/ebooks/$id' | '/ebooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRoute
  EbooksIdRoute: typeof EbooksIdRoute
  EbooksIndexRoute: typeof EbooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/': {
      id: '/ebooks/'
      path: '/ebooks'
      fullPath: '/ebooks/'
      preLoaderRoute: typeof EbooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/$id': {
      id: '/ebooks/$id'
      path: '/ebooks/$id'
      fullPath: '/ebooks/$id'
      preLoaderRoute: typeof EbooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRoute,
  EbooksIdRoute: EbooksIdRoute,
  EbooksIndexRoute: EbooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
